#
# YAML Configuration File - app
#     Application Configuration File
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---

app:
  name: "Welcome to Packfire Framework"
  version: "1.0"
  rootUrl: "http://localhost/packfire"
  debug: true

security:
  disabled: true
  override: false
  identity: null
  
session:
  enabled: false
  name: packfire
  lifetime: 3600
  http: true
  secure: false

routing:
  enabled: true
  caching: false

database:
#  default: 
#    driver: mysql
#    host: localhost
#    dbname: packfire
#    user: root 
#    password: password

...