#
# YAML Configuration File - IoC
#     Inversion of Control - services definition
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---
#serviceName:
#  class: className
#  parameters:
#    - param1
#    - param2

#security: # the security module is optional. The default security module does not identify or authenticate the users
#  class: app.AppSecurityModule

# the messenger service
messenger:
  class: packfire.session.pMessenger

#set the session storage method
session.storage:
  class: packfire.session.storage.pSessionStorage
  parameters: []
  
# set the cache to use
cache:
  class: packfire.cache.pFileCache
  
# this sets the debugger output method
debugger.output:
  class: packfire.debugger.firebug.pFirebugDebugOutput

...