#
# YAML Configuration File - app
#     Application Configuration File
#
# Author: Sam-Mauris Yong / mauris@hotmail.sg
# License: http://www.opensource.org/licenses/bsd-license New BSD License
#

---
app:
  name: "Packfire Framework for PHP"
  version: "1.0-sofia"
  rootUrl: "http://localhost/packfire/public"
  debug: false
  
session:
  name: packfire
  lifetime: 3600
  http: true
  secure: false

routing:
  enabled: true

database:
#  default: 
#    driver: mysql
#    host: localhost
#    dbname: packfire
#    user: root 
#    password: password

...