#
# YAML Configuration File - routing
#     Routing for the CLI application goes here
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---

install:
  actual: "controller.pSetupController:installFramework"
  remap:
    'i': 'root'
    'install': 'root'
  params:
    root: any
    
createProfile:
  actual: "controller.pSetupController:createApplication"
  remap:
    'c': 'root'
    'create': 'root'
    'p': 'packfire'
  params:
    root: any
    packfire: any
    
create:
  actual: "controller.pSetupController:createApplication"
  remap:
    'c': 'root'
    'create': 'root'
  params:
    root: any

phpunitRun:
  actual: "controller.pSetupController:unitTest"
  remap:
    't': 'test'
  params:
    'test': value/true

phpunitRun2:
  actual: "controller.pSetupController:unitTest"
  params:
    1: 'test'

packfireVersion:
  actual: "controller.pSetupController:version"
  remap:
    'v': 'version'
  params:
    'version': value/true

packfireVersion:
  actual: "controller.pSetupController:version"
  params:
    1: 'version'

home:
  actual: "controller.pSetupController:welcome"

...